title: Brandon Cardoso
description: Software Engineer from Toronto, Canada.

author:
    name: Brandon Cardoso
    email: brandon@bcardo.so

hima:
    social:
        - { platform: github, url: 'https://github.com/brandoncardoso', label: "my github profile" }
        - { platform: linkedin, url: 'https://linkedin.com/in/brandoncardoso', label: "my linkedin profile" }
        - { platform: instagram, url: 'https://instagram.com/bcardo.so', label: "my instagram page" }

google_analytics_measurement_id: G-8FVYBBB8TK

remote_theme: brandoncardoso/hima

url: https://www.bcardo.so

header_pages:
    - projects.html

plugins:
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-feed
