title: Brandon Cardoso
description: Software Engineer from Toronto, Canada.

author:
    name: Brandon Cardoso
    email: brandon@bcardo.so

permalink: /:slugified_categories/:title:output_ext

defaults:
    -
        scope:
            path: "_posts"
        values:
            layout: "post"
    -
        scope:
            path: "_posts/becoming-a-better-software-engineer"
        values:
            category: "becoming a better software engineer"

hima:
    date_format: "%b. %-d, %Y"
    social:
        - { platform: github, url: 'https://github.com/brandoncardoso', label: "my github profile" }
        - { platform: linkedin, url: 'https://linkedin.com/in/brandoncardoso', label: "my linkedin profile" }
        - { platform: instagram, url: 'https://instagram.com/bcardo.so', label: "my instagram page" }

google_analytics_measurement_id: G-8FVYBBB8TK

remote_theme: brandoncardoso/hima

url: https://www.bcardo.so

header_pages:
    - projects.html
    - posts.html

jekyll-archives:
    enabled:
        - categories
        - tags
    layout: archive

plugins:
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-feed
    - jekyll-archives
