name: Brandon Cardoso
url: https://bcardo.so
title: Brandon Cardoso
description: "A software engineer from Toronto, Canada."

date_format: "%d %b %Y"

markdown: kramdown
timezone: America/Toronto

plugins:
    - jekyll-sitemap

defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: "post"
        values:
            layout: "post"
            customClass: "post"
            author: "Brandon Cardoso"
