# File: .github/workflows/redeploy.yml
name: Redeploy

on:
  workflow_dispatch:

jobs:
  redeploy:
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
            --header "Authorization: Bearer ${{ secrets.USER_TOKEN }}"
        env:
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
